# Generated by Django 5.0.6 on 2024-06-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_db', '0002_clientes_historialclientes_delete_credithistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='historialclientes',
            options={'managed': False},
        ),
    ]
